CaseManager= "//a[@href='#/caseTracker']"
Case_Search_Text="//*[@id='home']/section[2]/div[1]/div[1]/div[1]/div/input"
Case_Search="//*[@id='home']/section[2]/div[1]/div[1]/div[2]/button"
Advanced_Search="xpath=//a[contains(text(),'Advanced Search')]"
Final_Pending="xpath=//a[contains(text(),'Final Pending')]"
Interim_Published="xpath=//a[contains(text(),'Interim Published')]"
YTR="xpath=//a[contains(text(),'YTR')]"
Insuff="xpath=//a[contains(text(),'Insuff')]"
WIP="xpath=//a[contains(text(),'WIP')]"
Stop_case_Tab="xpath=//a[contains(text(),'Stopped')]"
Stop_case="xpath=//span[@title='Stop Case']"
Stop_Case_Comment="xpath=//textarea[@placeholder='Stop comments']"
Stop_Case_button="//button[text()='Stop Case']"
Case_Modify="xpath=//span[@class='glyphicon glyphicon-pencil']"
Add_Component="xpath=//button[text()='Add Component']"
Delete_Component="xpath=//button[text()='Delete Component']"
